- name: Install PulseAudio
  pacman:
    name:
      - pulseaudio
      - pulseaudio-alsa
      - alsa-utils
    state: present

- name: Add the user in group of audio
  user:
    name: '{{ user.name }}'
    group: audio
