---
- name: Install wpa_supplicant
  pacman:
    name: wpa_supplicant
    state: present


# Create your own wpa_supplicant configuration file by renaming
# files/wpa_supplicant-template.conf to match the your network interface. If
# this file is to be hosted publically (e.g. GitHub), you MUST encrypt it using
# the ansible-vault utility.
- name: Create wpa_supplicant interface file
  copy:
    src: 'wpa_supplicant-{{ wifi.interface }}.conf'
    dest: '/etc/wpa_supplicant/wpa_supplicant-{{ wifi.interface }}.conf'
    mode: 0600
  notify: Reconfigure wpa_supplicant

- name: Enable network services
  systemd:
    name: '{{ item }}'
    enabled: True
    # Starting removed: wpa_supplicant@.service requires interface to be up,
    # disabled in task 'Install Broadcom DKMS driver'
    #state: started
  with_items:
    - systemd-networkd.service
    - 'wpa_supplicant@{{ wifi.interface }}.service'

