- name: Install OpenSSH and sshfs
  pacman:
    name:
      - openssh
      - sshfs
    state: present

- name: Enable and start SSH service
  systemd:
    name: sshd
    enabled: True
    state: started
