- name: Set environment variables for AUR user
  setup:
    filter: ansible_env

- name: Create AUR directory
  file:
    path: '/home/{{ user.name }}/aur'
    owner: '{{ user.name }}'
    state: directory

- name: Reset environment variables
  setup:
    filter: ansible_env
